version: 1.2 # The .dockstore.yml schema version
workflows:
  - name: phylophoenix
  - subclass: WDL
    primaryDescriptorPath: /workflows/wf_phylophoenix.wdl
    filter: 
      - branches:
        - main
        - dev
    readMePath: README.md
    authors:
      - orcid: 0000-0002-1308-3429