FROM mambaorg/micromamba:2.0.5

# metadata
LABEL base.image="mambaorg/micromamba:2.0.5"
LABEL dockerfile.version="2"
LABEL software="phylophoenix"
LABEL software.version="1.1.0"
LABEL description="PhyloPHoeNIx: A short-read phylogenetic pipeline for healthcare-associated and antimicrobial resistant pathogens"
LABEL website="https://github.com/cdcgov/phoenix/"
LABEL license="https://github.com/CDCgov/phoenix/blob/main/LICENSE"
LABEL maintainer="Jill Hagey"
LABEL maintainer.email="jvhagey@gmail.com"

#install conda in the base environment
#RUN conda install mamba -n base -c conda-forge
#RUN conda config --add channels defaults && \
#conda config --add channels bioconda && \
#conda config --add channels conda-forge

ENV CONDA_SOLVER=libmamba

# creating base environment
RUN micromamba create -n phylophoenix -c defaults -c bioconda -c conda-forge \
    conda-forge::python  \
    conda-forge::biopython \
    conda-forge::xz \
    anaconda::pandas \
    anaconda::openpyxl \
    conda-forge::rsync \
    conda-forge::xlsxwriter \
    conda-forge::ca-certificates \
    conda-forge::procps-ng \
    conda-forge::coreutils \
    conda-forge::gsutil \
    conda-forge::pyyaml \
    conda-forge::pigz \
    anaconda::git \
    anaconda::graphviz \
    conda-forge::libcurl \
    # need this for mash: error while loading shared libraries: libgsl.so.25: https://github.com/ParBLiSS/FastANI/issues/96
    conda-forge::gsl=2.7=he838d99_0 \
    # you need this not the Jetbrains versio of java https://github.com/nextflow-io/nextflow/issues/2841
    conda-forge::openjdk \
    bioconda::bcftools=1.22 \
    bioconda::htslib=1.23 \
    bioconda::fastqc=0.12.1 \
    bioconda::nextflow=25.04.2 && \
    micromamba clean -a -y
    #&& echo "source activate phylophoenix" >> ~/.bashrc

RUN micromamba create -n snvphyl-tools -c conda-forge bioconda::snvphyl-tools=1.8.2 -y
RUN micromamba create -n mash -c conda-forge bioconda::mash=2.3 -y 
RUN micromamba create -n samtools -c conda-forge bioconda::samtools=1.9 -y
RUN micromamba create -n freebayes -c conda-forge bioconda::freebayes=1.3.10 -y
RUN micromamba create -n smalt -c conda-forge bioconda::smalt=0.7.6 -y
RUN micromamba create -n phyml -c conda-forge bioconda::phyml=3.3.20220408 -y && micromamba clean -a -y

ENV PATH=/opt/conda/envs/phylophoenix/bin:/opt/conda/bin:/opt/conda/envs/env/bin:/opt/conda/envs/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
